# Generated by Django 5.1.3 on 2024-12-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='duty',
            field=models.CharField(default='surveyor', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='mission',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='year',
            field=models.DateField(blank=True, default='2024-01-01', help_text='The year I quit/finished work.'),
        ),
    ]
