# Generated by Django 5.1.3 on 2024-12-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_summary_job_duty_job_location_job_mission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-year']},
        ),
    ]
