# Generated by Django 5.1.3 on 2024-12-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_example_note_expression_note_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='source_url',
            field=models.URLField(default='https://none.com', max_length=511),
        ),
    ]
