# Generated by Django 5.1.3 on 2024-12-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_list_note_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, upload_to='static/'),
        ),
    ]
