# Generated by Django 5.1.3 on 2024-12-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, upload_to='kendir_info/static/'),
        ),
    ]
