# Generated by Django 5.1.3 on 2024-12-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_note_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
